### ISSUE TITLE
自启动问题

### ISSUE THREAD

**Issue by iQuick** [zjkhiyori/hack-root#6]
请问自启动 service ，有办法能获取到开发者权限吗。

**Comment by zjkhiyori** [comment]
请问开发者权限具体指的是什么权限。。？理论只要安卓设备开启了调试模式，我们的adb以及adb启动的服务都是具有开发者权限的

**Comment by zjkhiyori** [comment]
自启动指的是app内启动吗？这个估计不行哦，谷歌应该不会放任这种漏洞存在的

**Comment by iQuick** [comment]
之前用北通的的手柄时候感觉他们用的这种方式，通过外部 usb 设备去启动 service 获取权限，并开启屏幕点击映射。
但是看他们最新体验已经不需要外部设备去启动 service 了，能直接启动服务，这个楼主有思路吗？

**Comment by zjkhiyori** [comment]
> 之前用北通的的手柄时候感觉他们用的这种方式，通过外部 usb 设备去启动 service 获取权限，并开启屏幕点击映射。
> 但是看他们最新体验已经不需要外部设备去启动 service 了，能直接启动服务，这个楼主有思路吗？

你是说的北通安卓手柄吗？如果不是用的无障碍，那可能把启动服务的脚本烧录进了手柄内部芯片，插入usb的时候就帮你启动了

**Comment by iQuick** [comment]
并不是无障碍，也没有使用手柄通过 usb 去链接。以前是通过一个类似 u盘的激活器去启动，这种是烧写在这个控件主板上的，现在是不需要这个了。蓝牙连接就可以启动，开启屏幕映射了。

**Comment by zjkhiyori** [comment]
> 并不是无障碍，也没有使用手柄通过 usb 去链接。以前是通过一个类似 u盘的激活器去启动，这种是烧写在这个控件主板上的，现在是不需要这个了。蓝牙连接就可以启动，开启屏幕映射了。

也可能从蓝牙这块下手的，现阶段纯app基本都需要外部注入一下的
