### ISSUE TITLE
Execute the Script??

### ISSUE THREAD

**Issue by Hae14** [zjkhiyori/hack-root#8]
the Part "execute the Script".
How & what exactly do you do there?

**Comment by zjkhiyori** [comment]
pls see the below in doc 

* Foreground(service will close if you unplug the USB cable)
`bash scripts/launch_fore.sh `
* Background(will keep running unless restart the device or kill this service, service name is club.syachiku.hackrootservice )
`bash scripts/launch_silence.sh`

**Comment by Hae14** [comment]
where do i do that??
Terminal Emulator?? ADB? or what???

**Comment by zjkhiyori** [comment]
> where do i do that??
> Terminal Emulator?? ADB? or what???

In your terminal(Mac OS) or bash(Windows)
